# Site settings
title: pogoseat
email: support@pogoseat.com
description: "Pogoseat is an enterprise ticketing solution that enables sports teams and concert venues to offer their fans the opportunity to upgrade their seats and purchase unique VIP upgrades at live entertainment events."

# Color settings
color:
  primary: bb1329 
  secondary: a41124    
  secondary-dark: 333

# Team
people:
- name: Evan Owens
  pic: 1
  position: Founder & CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Abel Cuskelly
  pic: 2
  position: Founder & VP of Sales
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Andrew Hart
  pic: 3
  position: Founder & CTO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Zack Cuskelly
  pic: 4
  position: Founder & VP of Strategy
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Max Lebovitz
  pic: 5
  position: VP of Marketing
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rhett Fahrney
  pic: 6
  position: VP of Engineering
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Dave Trager
  pic: 7
  position: VP of Fan Experience
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Kiran Patel
  pic: 8
  position: Managing Director and UK Operation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Trey Davis
  pic: 9
  position: Managing Director & Founder of UK Operation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Bikramjit Singh
  pic: 10
  position: Full Stack Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Phill Crumm
  pic: 11
  position: Full Stack Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Eugene Wen
  pic: 12
  position: Front End Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


# Social Media
social:
  - title: twitter
    url: https://twitter.com/pogoseat
  - title: facebook
    url: https://www.facebook.com/pogoseat
  - title: instagram
    url: https://instagram.com/pogoseat/
  - title: pinterest 
    url: https://www.pinterest.com/pogoseat/
  - title: angellist
    url: https://angel.co/pogoseat

# Postal address (add as many lines as necessary)
address:
  - line: 555 Rose Ave Unit 2
  - line: Los Angeles, CA 90291

# Build settings
markdown: kramdown
permalink: pretty